# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nikki Bee Blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm currently doing an internship for Outreachy. Wow!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://http://nikkisquared.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  nikkisquared

# Build settings
markdown: kramdown
